{
 "title": "Flink",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JobManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "heap memory [{{instance}}]"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "non-heap memory [{{instance}}]"
      }
     ]
    },
    {
     "title": "GC Overhead",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time[5m])/1000 + rate(flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time[5m])/1000",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "heap memory [{{instance}}]"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "non-heap memory [{{instance}}]"
      }
     ]
    },
    {
     "title": "GC Overhead",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "checkout_attribution_job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Kafka Bytes Consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Event Time lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_currentEmitEventTimeLag",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInLocalPerSecond{job_name=\"checkout_attribution_job\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{job_name=\"checkout_attribution_job\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "repeat": "job",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=\"$job\"}"
    }
   ]
  }
 ]
}